import { db } from "./storage";
import { events, casualties, infrastructure } from "@shared/schema";
import { sql } from "drizzle-orm";

export function seedDatabase() {
  // Check if already seeded
  const count = db.select({ count: sql<number>`COUNT(*)` }).from(events).get();
  if (count && count.count > 0) return;

  // =============================================
  // EVENTS — based on reported conflict data
  // =============================================
  const eventData = [
    // Feb 27 — Order given
    {
      date: "2026-02-27T20:38:00Z",
      title: "Operation Epic Fury Authorized",
      description: "President Trump authorizes Operation Epic Fury, ordering joint US-Israeli military operations against Iran.",
      category: "diplomatic",
      actor: "US",
      target: "Iran Military Infrastructure",
      lat: 38.8977, lng: -77.0365,
      location: "Washington D.C.",
      country: "US",
      source: "CENTCOM",
      sourceUrl: "https://www.centcom.mil",
      severity: "critical",
    },
    // Feb 28 — Opening strikes
    {
      date: "2026-02-28T06:35:00Z",
      title: "CENTCOM Announces Airstrikes on Iran",
      description: "US Central Command announces joint airstrikes with partner forces against Iranian military targets. Tomahawk missiles launched from warships, HIMARS launchers deployed. B-2, B-1, and B-52 bombers strike fortified ballistic missile facilities.",
      category: "airstrike",
      actor: "US",
      target: "Ballistic Missile Facilities",
      lat: 35.6892, lng: 51.3890,
      location: "Tehran, Iran",
      country: "Iran",
      source: "CENTCOM",
      sourceUrl: "https://www.centcom.mil",
      severity: "critical",
    },
    {
      date: "2026-02-28T06:45:00Z",
      title: "IAF Decapitation Strikes on Iranian Leadership",
      description: "Israeli Air Force launches unprecedented wave of decapitation strikes. Supreme Leader Khamenei and several high officials killed at residential compound. Over 200 Israeli fighter jets deployed — largest combat sortie in Israel's history.",
      category: "airstrike",
      actor: "Israel",
      target: "Iranian Leadership / Supreme Leader Compound",
      lat: 35.7219, lng: 51.3347,
      location: "North Tehran, Iran",
      country: "Iran",
      source: "IDF",
      sourceUrl: "https://www.idf.il",
      severity: "critical",
    },
    {
      date: "2026-02-28T07:00:00Z",
      title: "Strikes on Command & Control Infrastructure",
      description: "US Navy, Air Force, and Marine Corps strike command-and-control infrastructure, UAV production sites, and radar installations across Iran.",
      category: "airstrike",
      actor: "Coalition",
      target: "C2 Infrastructure, UAV Sites, Radar",
      lat: 32.6546, lng: 51.6680,
      location: "Isfahan, Iran",
      country: "Iran",
      source: "CENTCOM",
      sourceUrl: "https://www.centcom.mil",
      severity: "critical",
    },
    {
      date: "2026-02-28T07:30:00Z",
      title: "Black Sparrow Missile First Combat Use",
      description: "Israel deploys the newly developed Black Sparrow air-launched ballistic missile from F-15s for the first time in combat operations against fortified Iranian targets.",
      category: "missile",
      actor: "Israel",
      target: "Fortified Military Targets",
      lat: 34.3142, lng: 47.0650,
      location: "Kermanshah, Iran",
      country: "Iran",
      source: "IDF",
      sourceUrl: "https://www.idf.il",
      severity: "major",
    },
    // Iranian retaliation
    {
      date: "2026-02-28T09:05:00Z",
      title: "Iran Launches Ballistic Missile Retaliation",
      description: "Iran launches approximately 170 ballistic missiles toward Israel and Gulf states in retaliation. Targets include Al Udeid (Qatar), Ali Al Salem (Kuwait), Al Dhafra (UAE), and US Fifth Fleet HQ (Bahrain).",
      category: "missile",
      actor: "Iran",
      target: "US/Coalition Military Bases, Israeli Cities",
      lat: 26.2235, lng: 50.5876,
      location: "Manama, Bahrain",
      country: "Bahrain",
      source: "IRGC",
      sourceUrl: null,
      severity: "critical",
    },
    {
      date: "2026-02-28T09:26:00Z",
      title: "Missile Strikes US Fifth Fleet in Bahrain",
      description: "Iranian ballistic missile strikes the USN Fifth Fleet service center in Bahrain. Explosions and smoke reported in Manama. Bahrain activates air-raid sirens.",
      category: "missile",
      actor: "Iran",
      target: "US Navy Fifth Fleet",
      lat: 26.2346, lng: 50.6109,
      location: "NSA Bahrain",
      country: "Bahrain",
      source: "Al Jazeera",
      sourceUrl: "https://www.aljazeera.com",
      severity: "critical",
    },
    {
      date: "2026-02-28T10:15:00Z",
      title: "Missile Strikes Confirmed in Israel",
      description: "IDF confirms missile impacts in Haifa and Tel Aviv. A strike on a residential area in Tel Aviv kills one civilian and injures 27. Israeli shelters activated nationwide.",
      category: "missile",
      actor: "Iran",
      target: "Israeli Cities — Haifa, Tel Aviv",
      lat: 32.0853, lng: 34.7818,
      location: "Tel Aviv, Israel",
      country: "Israel",
      source: "IDF / Reuters",
      sourceUrl: "https://www.reuters.com",
      severity: "critical",
    },
    {
      date: "2026-02-28T12:00:00Z",
      title: "Drone Strike Kills 6 US Soldiers in Kuwait",
      description: "A single Iranian drone strike on a US base in Kuwait kills six American service members from the 103rd Expeditionary Sustainment Command (Des Moines, Iowa).",
      category: "drone",
      actor: "Iran",
      target: "US Military Base, Kuwait",
      lat: 29.3375, lng: 47.9774,
      location: "Ali Al Salem Air Base, Kuwait",
      country: "Kuwait",
      source: "CENTCOM / NPR",
      sourceUrl: "https://www.npr.org",
      severity: "critical",
    },
    {
      date: "2026-02-28T14:00:00Z",
      title: "CENTCOM: Dismantling Iranian Security Apparatus",
      description: "CENTCOM declares it has been instructed to 'dismantle the Iranian regime's security apparatus.' Joint US-Israeli strikes continue against targets in Tehran, Sanandaj, and military installations.",
      category: "airstrike",
      actor: "Coalition",
      target: "Military Command Centers, Missile Sites",
      lat: 35.3219, lng: 46.9862,
      location: "Sanandaj, Iran",
      country: "Iran",
      source: "CENTCOM",
      sourceUrl: "https://www.centcom.mil",
      severity: "critical",
    },
    {
      date: "2026-02-28T15:00:00Z",
      title: "Strikes on Azadi Square and Tehran Metro",
      description: "Joint US-Israeli strike targets Azadi Square in Tehran along with military facilities and a metro station. IAF strikes Iranian military complex in eastern Tehran.",
      category: "airstrike",
      actor: "Coalition",
      target: "Azadi Square, Military Complex, Metro Station",
      lat: 35.6997, lng: 51.3380,
      location: "Tehran, Iran",
      country: "Iran",
      source: "IDF / CENTCOM",
      sourceUrl: null,
      severity: "major",
    },
    {
      date: "2026-02-28T16:15:00Z",
      title: "Major Military Outpost Destroyed",
      description: "Israel announces completion of large-scale airstrikes on a major military outpost housing soldiers from all branches of Iran's security apparatus. Basij headquarters struck, along with missile launch pads and defense systems.",
      category: "airstrike",
      actor: "Israel",
      target: "Basij HQ, Missile Launch Pads, Defense Systems",
      lat: 35.7000, lng: 51.4200,
      location: "Tehran Area, Iran",
      country: "Iran",
      source: "IDF",
      sourceUrl: "https://www.idf.il",
      severity: "critical",
    },
    // March 1
    {
      date: "2026-03-01T08:00:00Z",
      title: "Beit Shemesh Missile Strike — 9 Killed",
      description: "Iranian ballistic missile strikes central Israel's Beit Shemesh, killing 9 people and injuring over 20 in a residential area.",
      category: "missile",
      actor: "Iran",
      target: "Beit Shemesh, Residential Area",
      lat: 31.7466, lng: 34.9879,
      location: "Beit Shemesh, Israel",
      country: "Israel",
      source: "Israeli Health Ministry",
      sourceUrl: "https://www.reuters.com",
      severity: "critical",
    },
    {
      date: "2026-03-01T10:00:00Z",
      title: "Israel Resumes Major Strikes on Lebanon",
      description: "Israel resumes extensive military operations in Lebanon. Death toll reaches 968 with at least 100 children killed. Over one million displaced since conflict began.",
      category: "airstrike",
      actor: "Israel",
      target: "Hezbollah Targets, Lebanon",
      lat: 33.8938, lng: 35.5018,
      location: "Beirut, Lebanon",
      country: "Lebanon",
      source: "Al Jazeera",
      sourceUrl: "https://www.aljazeera.com",
      severity: "critical",
    },
    {
      date: "2026-03-01T14:00:00Z",
      title: "Drones Target Port of Duqm, Oman",
      description: "Two drones target the Port of Duqm in Oman, injuring one foreign worker. Separately, a Palau-flagged oil tanker attacked near Oman's coast, four people injured.",
      category: "drone",
      actor: "Iran",
      target: "Port of Duqm, Oil Tanker",
      lat: 19.6745, lng: 57.7075,
      location: "Duqm, Oman",
      country: "Oman",
      source: "Reuters",
      sourceUrl: "https://www.reuters.com",
      severity: "moderate",
    },
    // March 2
    {
      date: "2026-03-02T12:00:00Z",
      title: "US Death Toll Rises to 6 Confirmed KIA",
      description: "US announces fatalities have risen to six with four others seriously injured. Four victims identified as members of the 103rd Expeditionary Sustainment Command, Iowa.",
      category: "humanitarian",
      actor: "US",
      target: "Casualty Report",
      lat: 29.3375, lng: 47.9774,
      location: "Kuwait",
      country: "Kuwait",
      source: "CENTCOM",
      sourceUrl: "https://www.centcom.mil",
      severity: "major",
    },
    // March 6
    {
      date: "2026-03-06T08:00:00Z",
      title: "Heavy Strikes on Tehran — Mehrabad Airport Hit",
      description: "US and Israel execute heavy airstrikes on Tehran targeting Mehrabad airport, a police station, an IRGC base, and residential units. HRANA records 664 attacks in 28 provinces.",
      category: "airstrike",
      actor: "Coalition",
      target: "Mehrabad Airport, IRGC Base, Police Station",
      lat: 35.6892, lng: 51.3115,
      location: "Tehran, Iran",
      country: "Iran",
      source: "HRANA",
      sourceUrl: "https://www.hrana.org",
      severity: "critical",
    },
    {
      date: "2026-03-06T10:00:00Z",
      title: "Strikes on Kermanshah, Western Iran",
      description: "Coalition airstrikes target Kermanshah as well as Salmas, Maku, and Saqqez in western Iran. At least 25 casualties reported including 4 civilian deaths.",
      category: "airstrike",
      actor: "Coalition",
      target: "Military Targets, Western Iran",
      lat: 34.3142, lng: 47.0650,
      location: "Kermanshah, Iran",
      country: "Iran",
      source: "HRANA",
      sourceUrl: "https://www.hrana.org",
      severity: "major",
    },
    // March 10
    {
      date: "2026-03-10T12:00:00Z",
      title: "Iranian Military Death Toll Exceeds 3,900",
      description: "Hengaw Organization for Human Rights estimates 3,900+ members of Iranian military forces killed in airstrikes. Military casualties significantly higher than reported figures.",
      category: "humanitarian",
      actor: "Coalition",
      target: "Iranian Military Forces",
      lat: 35.6892, lng: 51.3890,
      location: "Across Iran",
      country: "Iran",
      source: "Hengaw Organization",
      sourceUrl: null,
      severity: "critical",
    },
    // March 13
    {
      date: "2026-03-13T06:00:00Z",
      title: "US Refueling Aircraft Crash — 6 Crew Killed",
      description: "All six crew members aboard a US refueling aircraft killed when it crashes in western Iraq. CENTCOM confirms the loss.",
      category: "ground",
      actor: "US",
      target: "US Aircraft Loss",
      lat: 33.3128, lng: 44.3615,
      location: "Western Iraq",
      country: "Iraq",
      source: "CENTCOM",
      sourceUrl: "https://www.centcom.mil",
      severity: "major",
    },
    // March 14
    {
      date: "2026-03-14T12:00:00Z",
      title: "Iranian Military Deaths Exceed 4,400",
      description: "Updated estimates from Hengaw put Iranian military deaths at 4,400+. IDF estimates between 3,000-4,000 Iranian soldiers and commanders killed.",
      category: "humanitarian",
      actor: "Coalition",
      target: "Iranian Military Personnel",
      lat: 35.6892, lng: 51.3890,
      location: "Iran (nationwide)",
      country: "Iran",
      source: "Hengaw / IDF",
      sourceUrl: null,
      severity: "critical",
    },
    // March 16
    {
      date: "2026-03-16T10:00:00Z",
      title: "CENTCOM: 7,000+ Locations Struck in Iran",
      description: "CENTCOM announces US forces have struck over 7,000 locations in Iran since February 28. IRGC claims responsibility for attacks on at least 27 bases hosting US troops.",
      category: "airstrike",
      actor: "Coalition",
      target: "7,000+ Military Targets",
      lat: 32.6546, lng: 51.6680,
      location: "Iran (nationwide)",
      country: "Iran",
      source: "CENTCOM",
      sourceUrl: "https://www.centcom.mil",
      severity: "critical",
    },
    // March 17
    {
      date: "2026-03-17T12:00:00Z",
      title: "HRANA Documents 3,114 Deaths in Iran",
      description: "HRANA documents 3,114 deaths in Iran: 1,354 civilians, 1,138 military personnel, 622 unclassified. Notes military casualties are significantly higher due to limited access.",
      category: "humanitarian",
      actor: "Coalition",
      target: "Casualty Documentation",
      lat: 35.6892, lng: 51.3890,
      location: "Iran",
      country: "Iran",
      source: "HRANA",
      sourceUrl: "https://www.hrana.org",
      severity: "critical",
    },
    // Key leadership kills
    {
      date: "2026-02-28T07:30:00Z",
      title: "Iranian Defense Minister Nasirzadeh Killed",
      description: "Iranian defense minister Aziz Nasirzadeh and IRGC commander Mohammad Pakpour confirmed killed by Israeli airstrikes. IDF confirms deaths of seven Iranian security leaders.",
      category: "airstrike",
      actor: "Israel",
      target: "Iranian Defense Minister, IRGC Commander",
      lat: 35.7000, lng: 51.4000,
      location: "Tehran, Iran",
      country: "Iran",
      source: "IDF / Iran International",
      sourceUrl: null,
      severity: "critical",
    },
    {
      date: "2026-02-28T08:00:00Z",
      title: "40 Iranian Officials Killed in Opening Strikes",
      description: "CBS News reports intelligence sources confirm 40 Iranian officials killed in the initial strikes. Iran's Foreign Ministry states military has lost control over several units.",
      category: "airstrike",
      actor: "Coalition",
      target: "Iranian Government Officials",
      lat: 35.6892, lng: 51.3890,
      location: "Multiple locations, Iran",
      country: "Iran",
      source: "CBS News",
      sourceUrl: "https://www.cbsnews.com",
      severity: "critical",
    },
    // Minab school strike
    {
      date: "2026-02-28T08:30:00Z",
      title: "Girls' School Strike in Minab — 168 Killed",
      description: "A missile strike on a girls' elementary school adjacent to a naval base in Minab, near Bandar Abbas, kills approximately 168 schoolgirls. One of the deadliest single incidents.",
      category: "airstrike",
      actor: "Coalition",
      target: "Girls' School Adjacent to Naval Base",
      lat: 27.0783, lng: 57.0831,
      location: "Minab, Hormozgan Province, Iran",
      country: "Iran",
      source: "Britannica / HRANA",
      sourceUrl: "https://www.britannica.com/event/2026-Iran-War",
      severity: "critical",
    },
    // Infrastructure damage report
    {
      date: "2026-03-07T12:00:00Z",
      title: "Red Crescent: 6,668 Civilian Units Targeted",
      description: "Iranian Red Crescent reports over 6,668 civilian units targeted: 5,535 residential units, 1,041 commercial, 14 medical centres, 65 schools, 13 Red Crescent centres.",
      category: "humanitarian",
      actor: "Coalition",
      target: "Civilian Infrastructure",
      lat: 35.6892, lng: 51.3890,
      location: "Iran (nationwide)",
      country: "Iran",
      source: "Iranian Red Crescent Society",
      sourceUrl: null,
      severity: "critical",
    },
    // March 18
    {
      date: "2026-03-18T12:00:00Z",
      title: "Military Deaths Exceed 5,300",
      description: "Hengaw estimates 5,300+ Iranian military forces killed. Civilian death toll from HRANA at 1,354+ with 18,551 injured per Iranian Health Ministry.",
      category: "humanitarian",
      actor: "Coalition",
      target: "Casualty Update",
      lat: 35.6892, lng: 51.3890,
      location: "Iran",
      country: "Iran",
      source: "Hengaw Organization",
      sourceUrl: null,
      severity: "critical",
    },
    // March 21 — CENTCOM 8,000 target milestone
    {
      date: "2026-03-21T14:00:00Z",
      title: "CENTCOM: 8,000+ Targets Struck, 130 Naval Vessels Destroyed",
      description: "Admiral Brad Cooper announces US forces have struck over 8,000 military targets including 130 Iranian vessels — the largest elimination of a navy over a 3-week period since WWII. Over 8,000 combat flights flown with full air superiority. Iran's navy is no longer operating, aircraft grounded, missile/drone launch capability sharply declined.",
      category: "airstrike",
      actor: "US",
      target: "8,000+ Military Targets, 130 Naval Vessels",
      lat: 27.1536, lng: 56.1726,
      location: "Iranian Coastline / Nationwide",
      country: "Iran",
      source: "CENTCOM / Admiral Brad Cooper",
      sourceUrl: "https://thehill.com/policy/defense/5794604-centcom-brad-cooper-us-military-operation-iran-8k-targets/",
      severity: "critical",
    },
    {
      date: "2026-03-21T10:00:00Z",
      title: "US Strikes Natanz Nuclear Facility with Bunker Busters",
      description: "US conducts strikes on the Natanz Nuclear Facility using bunker buster bombs. Russia condemns the strikes as a 'blatant violation of international law.' IAEA urges military restraint to avoid nuclear accident risk.",
      category: "airstrike",
      actor: "US",
      target: "Natanz Nuclear Facility",
      lat: 33.7225, lng: 51.7278,
      location: "Natanz, Isfahan Province, Iran",
      country: "Iran",
      source: "Wikipedia / IAEA",
      sourceUrl: "https://en.wikipedia.org/wiki/2026_Iran_war",
      severity: "critical",
    },
    {
      date: "2026-03-21T16:00:00Z",
      title: "Iran Retaliates — Strikes Dimona, 78+ Injured",
      description: "In response to Natanz strikes, Iran fires missiles at the southern Israeli town of Dimona, home to Israel's main nuclear facility. At least 78 people injured in Dimona and nearby Arad.",
      category: "missile",
      actor: "Iran",
      target: "Dimona Nuclear Facility Area, Israel",
      lat: 31.0680, lng: 35.2063,
      location: "Dimona, Israel",
      country: "Israel",
      source: "Al Jazeera",
      sourceUrl: "https://www.aljazeera.com/news/2026/3/1/us-israel-attacks-on-iran-death-toll-and-injuries-live-tracker",
      severity: "critical",
    },
    // March 21 — 5,000-lb bombs on underground facility
    {
      date: "2026-03-21T08:00:00Z",
      title: "5,000-lb Bombs Destroy Underground Coastal Missile Facility",
      description: "US drops multiple 5,000-lb bombs on a hardened underground facility along Iran's coastline used to store anti-ship cruise missiles, mobile missile launchers, and equipment threatening international shipping. Intelligence support sites and radar relay systems also destroyed.",
      category: "airstrike",
      actor: "US",
      target: "Underground Anti-Ship Missile Facility",
      lat: 26.5577, lng: 54.3614,
      location: "Southern Iran Coastline",
      country: "Iran",
      source: "CENTCOM",
      sourceUrl: "https://www.kurdistan24.net/en/story/902191/centcom-cites-air-superiority-and-8000-strikes-in-operations-against-iran",
      severity: "critical",
    },
    // March 24 — UAE/Bahrain casualties, US wounded update
    {
      date: "2026-03-24T12:00:00Z",
      title: "290 US Service Members Wounded — 255 Returned to Duty",
      description: "CENTCOM confirms approximately 290 US service members wounded since start of Operation Epic Fury. The vast majority were minor injuries; more than 255 troops have returned to duty. Total 13 US service members killed.",
      category: "humanitarian",
      actor: "US",
      target: "US Casualty Update",
      lat: 25.3548, lng: 51.1839,
      location: "Multiple US Bases, Middle East",
      country: "Qatar",
      source: "CENTCOM / Anadolu Agency",
      sourceUrl: "https://www.aa.com.tr/en/americas/nearly-290-us-service-members-wounded-in-operation-epic-fury-against-iran-centcom/3877898",
      severity: "major",
    },
    // March 24 — HRANA updated death toll
    {
      date: "2026-03-24T12:00:00Z",
      title: "HRANA: 3,389 Killed in Iran Including 1,527 Civilians",
      description: "US-based rights group HRANA reports 3,389 people killed in Iran since war erupted, with 1,527 confirmed as civilians. Casualties include strikes on schools, hospitals, and nonmilitary sites.",
      category: "humanitarian",
      actor: "Coalition",
      target: "Casualty Documentation",
      lat: 35.6892, lng: 51.3890,
      location: "Iran (nationwide)",
      country: "Iran",
      source: "HRANA / Reuters",
      sourceUrl: "https://www.reuters.com/world/middle-east/how-many-people-have-been-killed-us-israel-war-iran-2026-03-24/",
      severity: "critical",
    },
    // March 26 — 10,000 target milestone
    {
      date: "2026-03-26T12:00:00Z",
      title: "US Strikes 10,000th Target — 92% of Iran's Largest Vessels Destroyed",
      description: "Admiral Brad Cooper announces US has struck its 10,000th target. 92% of Iran's navy's largest vessels destroyed. Iran drone and missile launch rates down 90%. Two-thirds of military manufacturing capacity destroyed or heavily damaged. Over 10,000 combat flights flown.",
      category: "airstrike",
      actor: "US",
      target: "10,000+ Military Targets",
      lat: 35.6892, lng: 51.3890,
      location: "Iran (nationwide)",
      country: "Iran",
      source: "CENTCOM / Jerusalem Post",
      sourceUrl: "https://www.jpost.com/middle-east/iran-news/article-891222",
      severity: "critical",
    },
    // March 26 — Trump extends deadline for energy strikes
    {
      date: "2026-03-26T18:00:00Z",
      title: "Trump Extends Deadline for Iran Energy Strikes to April 6",
      description: "President Trump extends deadline for strikes on Iran's power plants by 10 more days to April 6, citing 'positive developments' in negotiations. Iran must reopen the Strait of Hormuz. Diplomacy under fire continues alongside military preparations.",
      category: "diplomatic",
      actor: "US",
      target: "Diplomatic / Strait of Hormuz",
      lat: 26.5960, lng: 56.2700,
      location: "Strait of Hormuz",
      country: "Iran",
      source: "NBC News / NYT",
      sourceUrl: "https://www.nbcnews.com/nightly-news/video/trump-extends-deadline-for-iran-strikes-amid-talks-260161093825",
      severity: "major",
    },
    // March 27 — Prince Sultan Air Base strike
    {
      date: "2026-03-27T10:00:00Z",
      title: "Iranian Strike on Prince Sultan Air Base Injures US Troops",
      description: "Iranian state media shows a strike at Prince Sultan Air Base in Saudi Arabia that injured several US service members. Casualty numbers unclear.",
      category: "missile",
      actor: "Iran",
      target: "Prince Sultan Air Base, Saudi Arabia",
      lat: 24.0623, lng: 47.5802,
      location: "Prince Sultan Air Base, Saudi Arabia",
      country: "Saudi Arabia",
      source: "CNN",
      sourceUrl: "https://www.cnn.com/2026/03/27/world/video/ebof-iran-war-attack-us-servicemembers-injured-jim-sciutto-kristen-holmes",
      severity: "major",
    },
    // March 27 — Civilian death toll update
    {
      date: "2026-03-27T12:00:00Z",
      title: "Nearly 1,500 Iranian Civilians Killed — Washington Post",
      description: "Washington Post reports nearly 1,500 Iranian civilians killed in dozens of US and Israeli strikes hitting schools, hospitals, and nonmilitary sites. Iran Health Ministry: 1,937 total dead, 24,800+ injured including 240 women and 212 children.",
      category: "humanitarian",
      actor: "Coalition",
      target: "Civilian Casualty Report",
      lat: 35.6892, lng: 51.3890,
      location: "Iran (nationwide)",
      country: "Iran",
      source: "Washington Post / Iran Health Ministry",
      sourceUrl: "https://www.washingtonpost.com/national-security/2026/03/27/iran-war-civilian-deaths/",
      severity: "critical",
    },
    // March 28 — Houthis enter war
    {
      date: "2026-03-28T06:00:00Z",
      title: "Houthis Enter War — Fire Ballistic Missile at Israel from Yemen",
      description: "Houthis launch ballistic missile at 'sensitive' Israeli military installations, coordinating with Iran and Hezbollah. IDF intercepts the missile. Houthis declare attacks will persist 'until aggression against all resistance fronts ceases.' Major escalation introducing new theater.",
      category: "missile",
      actor: "Houthi",
      target: "Israeli Military Installations",
      lat: 32.0853, lng: 34.7818,
      location: "Israel (intercepted)",
      country: "Israel",
      source: "NYT",
      sourceUrl: "https://www.nytimes.com/live/2026/03/28/world/iran-war-trump-israel-oil",
      severity: "critical",
    },
    // March 28 — Iran missile barrage on Israel, 1 killed
    {
      date: "2026-03-28T08:00:00Z",
      title: "Iran Missile Barrage Kills 1 in Tel Aviv, Several Injured",
      description: "Iran fires missile barrage at southern and central Israel. One man killed, several injured in Tel Aviv. IAF intercepts over 90% of drones launched by Iran and Hezbollah. IDF conducts wave of retaliatory strikes on Beirut.",
      category: "missile",
      actor: "Iran",
      target: "Tel Aviv, Southern/Central Israel",
      lat: 32.0853, lng: 34.7818,
      location: "Tel Aviv, Israel",
      country: "Israel",
      source: "Jerusalem Post",
      sourceUrl: "https://www.jpost.com/middle-east/iran-news/2026-03-27/live-updates-891386",
      severity: "critical",
    },
    // March 28 — Bushehr nuclear plant struck
    {
      date: "2026-03-28T07:00:00Z",
      title: "Missile Strikes Bushehr Nuclear Plant",
      description: "Atomic Energy Organization of Iran reports a missile strike on the Bushehr nuclear power plant. Details on damage unclear. Follows earlier strikes on Natanz and reports of IDF striking Khandab heavy water reactor and Ardakan yellowcake facility.",
      category: "missile",
      actor: "Coalition",
      target: "Bushehr Nuclear Power Plant",
      lat: 28.8312, lng: 50.8870,
      location: "Bushehr, Iran",
      country: "Iran",
      source: "Jerusalem Post / AEOI",
      sourceUrl: "https://www.jpost.com/middle-east/iran-news/2026-03-27/live-updates-891386",
      severity: "critical",
    },
    // March 28 — IDF strikes on Iranian nuclear facilities
    {
      date: "2026-03-28T09:00:00Z",
      title: "IDF Strikes Khandab Reactor and Ardakan Yellowcake Facility",
      description: "IDF confirms strikes on the Khandab heavy water reactor near Arak after calling for civilian evacuations. Iran reports hit on Ardakan yellowcake production facility. Iran FM Araghchi threatens retaliation.",
      category: "airstrike",
      actor: "Israel",
      target: "Khandab Heavy Water Reactor, Ardakan Yellowcake Facility",
      lat: 34.3731, lng: 49.2434,
      location: "Arak / Ardakan, Iran",
      country: "Iran",
      source: "IDF / Jerusalem Post",
      sourceUrl: "https://www.jpost.com/middle-east/iran-news/2026-03-27/live-updates-891386",
      severity: "critical",
    },
    // March 28 — IDF wave of strikes on Beirut
    {
      date: "2026-03-28T10:00:00Z",
      title: "IDF Conducts Wave of Strikes on Beirut",
      description: "Following Iran/Hezbollah missile and drone attacks on Israel, IDF conducts major wave of retaliatory strikes on Beirut, Lebanon. Conflict continues to expand across multiple fronts.",
      category: "airstrike",
      actor: "Israel",
      target: "Hezbollah Targets, Beirut",
      lat: 33.8938, lng: 35.5018,
      location: "Beirut, Lebanon",
      country: "Lebanon",
      source: "Jerusalem Post",
      sourceUrl: "https://www.jpost.com/middle-east/iran-news/2026-03-27/live-updates-891386",
      severity: "critical",
    },
    // =============================================
    // WEEK 2: March 29 - April 4, 2026
    // =============================================
    // April 1 — CENTCOM 12,300 targets, 155 vessels
    {
      date: "2026-04-01T12:00:00Z",
      title: "CENTCOM: 12,300+ Targets Struck, 155 Naval Vessels Destroyed",
      description: "CENTCOM announces US forces have struck over 12,300 targets including 155+ Iranian naval vessels destroyed or damaged. Wide range of strategic bombers, fighter aircraft, drones, and missile defense systems employed. 13 US service members killed, 303 wounded since Feb 28.",
      category: "airstrike",
      actor: "US",
      target: "12,300+ Military Targets",
      lat: 35.6892, lng: 51.3890,
      location: "Iran (nationwide)",
      country: "Iran",
      source: "CENTCOM / ANews",
      sourceUrl: "https://www.anews.com.tr/americas/2026/04/01/us-says-over-12300-targets-hit-in-iran-as-military-operation-continues/amp",
      severity: "critical",
    },
    // April 1 — IDF strikes weapons production
    {
      date: "2026-04-01T14:00:00Z",
      title: "IDF Strikes 15 Weapons Production Sites Including MODAFL Missile Complex",
      description: "IDF strikes approximately 15 weapons production sites including a Ministry of Defense and Armed Forces Logistics (MODAFL) complex for advanced ballistic missile production. Also struck a pharmaceutical company supplying fentanyl precursors usable for chemical weapons.",
      category: "airstrike",
      actor: "Israel",
      target: "MODAFL Complex, Weapons Production Sites",
      lat: 35.6892, lng: 51.3890,
      location: "Tehran / Multiple Provinces, Iran",
      country: "Iran",
      source: "IDF / Critical Threats",
      sourceUrl: "https://www.criticalthreats.org/analysis/iran-update-evening-special-report-april-1-2026",
      severity: "critical",
    },
    // April 1 — Iran 10-missile salvo at Israel
    {
      date: "2026-04-01T10:00:00Z",
      title: "Iran Launches 10-Missile Salvo at Israel — Largest Since War Began",
      description: "Iran fires five missile salvos at Israel including a 10-missile salvo, the largest single salvo targeting Israel since the war began. Cluster munitions hit three sites in central Israel including Bnei Barak, injuring at least 10 civilians. Coordinated with Hezbollah and Houthis.",
      category: "missile",
      actor: "Iran",
      target: "Central Israel — Bnei Barak",
      lat: 32.0853, lng: 34.7818,
      location: "Bnei Barak / Central Israel",
      country: "Israel",
      source: "Critical Threats / IDF",
      sourceUrl: "https://www.criticalthreats.org/analysis/iran-update-evening-special-report-april-1-2026",
      severity: "critical",
    },
    // April 1 — Iran drones + missiles target Bahrain
    {
      date: "2026-04-01T08:00:00Z",
      title: "Iran Launches 19 Drones and 4 Ballistic Missiles at Bahrain",
      description: "Iran launches 19 drones and 4 ballistic missiles targeting Bahrain on April 1, including US-linked technology companies. Follows IRGC threat to target US-linked AI, communications, and advanced technology firms in retaliation.",
      category: "drone",
      actor: "Iran",
      target: "US Bases and Tech Companies, Bahrain",
      lat: 26.2235, lng: 50.5876,
      location: "Bahrain",
      country: "Bahrain",
      source: "Critical Threats",
      sourceUrl: "https://www.criticalthreats.org/analysis/iran-update-evening-special-report-april-1-2026",
      severity: "critical",
    },
    // April 1 — Houthis attack Israel (4th time)
    {
      date: "2026-04-01T16:00:00Z",
      title: "Houthis Fire Ballistic Missiles at Southern Israel — 4th Attack",
      description: "Houthis launch ballistic missiles at southern Israel, coordinating with Iran and Hezbollah. IDF intercepts all missiles. This marks the fourth Houthi attack on Israel since entering the war on March 28.",
      category: "missile",
      actor: "Houthi",
      target: "Southern Israel",
      lat: 31.2530, lng: 34.7915,
      location: "Southern Israel (intercepted)",
      country: "Israel",
      source: "Critical Threats",
      sourceUrl: "https://www.criticalthreats.org/analysis/iran-update-evening-special-report-april-1-2026",
      severity: "major",
    },
    // April 1 — Hezbollah 71 attacks in 24 hours
    {
      date: "2026-04-01T12:00:00Z",
      title: "Hezbollah Conducts 71 Attacks on Northern Israel in 24 Hours",
      description: "Hezbollah claims 71 attacks targeting northern Israeli communities and Israeli forces between March 31 and April 1. Hezbollah also shoots down an IAF drone over southern Lebanon with a surface-to-air missile.",
      category: "missile",
      actor: "Hezbollah",
      target: "Northern Israeli Communities, IDF Positions",
      lat: 33.2774, lng: 35.2033,
      location: "Northern Israel / Southern Lebanon",
      country: "Lebanon",
      source: "Critical Threats",
      sourceUrl: "https://www.criticalthreats.org/analysis/iran-update-evening-special-report-april-1-2026",
      severity: "critical",
    },
    // April 1 — Strikes on PMF in Iraq
    {
      date: "2026-04-01T09:00:00Z",
      title: "Coalition Strikes Kill PMF Brigade Commander in Iraq",
      description: "Combined US-Israeli force conducts two airstrikes on the 53rd Popular Mobilization Forces (PMF) Brigade HQ in Tal Afar, Ninewa Province. Second strike kills the 53rd Brigade commando regiment commander and three other PMF members. Brigade affiliated with Iran-backed Badr Organization.",
      category: "airstrike",
      actor: "Coalition",
      target: "53rd PMF Brigade HQ, Tal Afar",
      lat: 36.3755, lng: 42.4502,
      location: "Tal Afar, Ninewa Province, Iraq",
      country: "Iraq",
      source: "Critical Threats",
      sourceUrl: "https://www.criticalthreats.org/analysis/iran-update-evening-special-report-april-1-2026",
      severity: "major",
    },
    // April 1 — Iran attacks tanker near Qatar
    {
      date: "2026-04-01T06:00:00Z",
      title: "Iran Attacks Oil Tanker Near Qatar — Strait of Hormuz Leverage",
      description: "Iran attacks the Panamanian-flagged AQUA 1 oil tanker, leased by Qatari state energy firm, 17 nautical miles NW of Ras Laffan, Qatar. Iranian officials signal they will use Strait of Hormuz as post-war leverage and will not reopen it unless all US/Israeli attacks cease.",
      category: "naval",
      actor: "Iran",
      target: "AQUA 1 Oil Tanker (Qatari-leased)",
      lat: 25.9150, lng: 51.5300,
      location: "17nm NW of Ras Laffan, Qatar",
      country: "Qatar",
      source: "Critical Threats / Reuters",
      sourceUrl: "https://www.criticalthreats.org/analysis/iran-update-evening-special-report-april-1-2026",
      severity: "major",
    },
    // April 1 — Trump speech: "hit Iran extremely hard"
    {
      date: "2026-04-01T22:00:00Z",
      title: "Trump: US Will Hit Iran 'Extremely Hard' Over Next 2-3 Weeks",
      description: "In a 19-minute White House address, President Trump says the US will hit Iran 'extremely hard over the next two to three weeks.' Claims military success but offers no concrete exit timeline. Iran rejects ceasefire — intelligence assesses Tehran sees itself in a strong position.",
      category: "diplomatic",
      actor: "US",
      target: "Presidential Address",
      lat: 38.8977, lng: -77.0365,
      location: "Washington D.C.",
      country: "US",
      source: "NYT / CBS News",
      sourceUrl: "https://www.nytimes.com/live/2026/04/02/world/iran-war-trump-news",
      severity: "major",
    },
    // April 1 — Iran restoring bombed missile silos
    {
      date: "2026-04-01T15:00:00Z",
      title: "Iran Restoring Bombed Missile Silos to Operational Status",
      description: "US intelligence reports Iranian operatives are unearthing underground missile silos and bunkers previously hit by US/Israeli strikes, restoring them to operational status shortly after assaults. Indicates Iran's resilience and reconstitution capability.",
      category: "ground",
      actor: "Iran",
      target: "Underground Missile Infrastructure",
      lat: 33.7225, lng: 51.7278,
      location: "Multiple Provinces, Iran",
      country: "Iran",
      source: "NYT / US Intelligence",
      sourceUrl: "https://www.nytimes.com/live/2026/04/04/world/iran-war-trump-news",
      severity: "major",
    },
    // April 3 — F-15E shot down over Iran
    {
      date: "2026-04-03T10:00:00Z",
      title: "Iran Shoots Down US F-15E Fighter Jet — One Crew Rescued, One Missing",
      description: "Iran shoots down a US F-15E Strike Eagle over Iranian airspace. One crew member rescued by American forces. Second crew member missing — Iran's governor offers $60,000 bounty for capture. First manned US aircraft lost to enemy fire in Operation Epic Fury. 494th Fighter Squadron, 48th Fighter Wing from RAF Lakenheath.",
      category: "ground",
      actor: "Iran",
      target: "US F-15E Strike Eagle (494th FS)",
      lat: 32.5, lng: 52.0,
      location: "Central Iran",
      country: "Iran",
      source: "NBC News / Military Times",
      sourceUrl: "https://www.nbcnews.com/news/military/us-fighter-jet-went-iran-search-rescue-mission-underway-officials-say-rcna266523",
      severity: "critical",
    },
    // April 3 — A-10 damaged in rescue attempt
    {
      date: "2026-04-03T13:00:00Z",
      title: "A-10 Warthog Damaged by Iranian Fire During Rescue — Pilot Ejects Over Kuwait",
      description: "An A-10 Thunderbolt deployed for the F-15E search-and-rescue comes under Iranian fire. The damaged aircraft reaches Kuwaiti airspace before the pilot ejects. Pilot recovered safely. Two Blackhawk helicopters also targeted during rescue but crew unharmed.",
      category: "ground",
      actor: "Iran",
      target: "US A-10 Warthog, Blackhawk Helicopters",
      lat: 29.3375, lng: 47.9774,
      location: "Iran / Kuwait Airspace",
      country: "Kuwait",
      source: "NBC News / CBS News",
      sourceUrl: "https://www.cbsnews.com/live-updates/iran-war-us-trump-warns-more-coming-oil-gas-strait-hormuz/",
      severity: "critical",
    },
    // April 4 — Trump 48-hour ultimatum
    {
      date: "2026-04-04T12:00:00Z",
      title: "Trump: Iran Has 48 Hours to Reopen Hormuz or US Will 'Unleash Hell'",
      description: "President Trump warns Iran has 48 hours to reopen the Strait of Hormuz before the US unleashes 'hell.' Says 'time is running out.' Iran rejects the ultimatum — intelligence assesses Tehran will not engage in serious negotiations.",
      category: "diplomatic",
      actor: "US",
      target: "48-Hour Ultimatum / Strait of Hormuz",
      lat: 26.5960, lng: 56.2700,
      location: "Strait of Hormuz",
      country: "Iran",
      source: "CBS News / NYT",
      sourceUrl: "https://www.cbsnews.com/live-updates/iran-war-us-trump-warns-more-coming-oil-gas-strait-hormuz/",
      severity: "critical",
    },
    // April 1 — Iraqi militia drones target US in Syria
    {
      date: "2026-04-01T04:00:00Z",
      title: "Iranian-Backed Militias Launch Drones at US Base in Syria",
      description: "Iranian-backed Iraqi militias launch drones at US Qasrak Base in Hasakah Province, Syria. US air defenses intercept at least 5 drones on March 31, with more on April 1. Separately, 3 drones strike UK-owned Castrol Oil warehouse near Erbil, Iraq.",
      category: "drone",
      actor: "Iran",
      target: "US Qasrak Base, Syria / Castrol Warehouse, Iraq",
      lat: 36.7800, lng: 41.2300,
      location: "Hasakah, Syria / Erbil, Iraq",
      country: "Iraq",
      source: "Critical Threats",
      sourceUrl: "https://www.criticalthreats.org/analysis/iran-update-evening-special-report-april-1-2026",
      severity: "moderate",
    },
    // April 1 — US wounded total update
    {
      date: "2026-04-01T18:00:00Z",
      title: "US Wounded Total Reaches 348 — 15 Killed",
      description: "As of March 31, 348 US service members wounded since start of Operation Epic Fury. Majority have returned to duty, 6 remain seriously wounded. Total 15 US service members killed including 1 non-combat death.",
      category: "humanitarian",
      actor: "US",
      target: "US Casualty Update",
      lat: 25.3548, lng: 51.1839,
      location: "Multiple US Bases",
      country: "Qatar",
      source: "Military Times / CENTCOM",
      sourceUrl: "https://www.militarytimes.com/news/your-military/2026/04/03/us-fighter-jet-shot-down-over-iran/",
      severity: "major",
    },
  ];

  for (const e of eventData) {
    db.insert(events).values(e).run();
  }

  // =============================================
  // CASUALTIES — cumulative snapshots by date/side
  // =============================================
  const casualtyData = [
    // Iran casualties
    { date: "2026-02-28", country: "Iran", side: "Iran", killed: 555, wounded: 4200, militaryKilled: 380, civilianKilled: 175, source: "Iranian Red Crescent" },
    { date: "2026-03-02", country: "Iran", side: "Iran", killed: 280, wounded: 3100, militaryKilled: 200, civilianKilled: 80, source: "HRANA" },
    { date: "2026-03-04", country: "Iran", side: "Iran", killed: 310, wounded: 2800, militaryKilled: 220, civilianKilled: 90, source: "HRANA" },
    { date: "2026-03-06", country: "Iran", side: "Iran", killed: 190, wounded: 2500, militaryKilled: 130, civilianKilled: 60, source: "HRANA" },
    { date: "2026-03-10", country: "Iran", side: "Iran", killed: 350, wounded: 2100, militaryKilled: 280, civilianKilled: 70, source: "Hengaw" },
    { date: "2026-03-14", country: "Iran", side: "Iran", killed: 290, wounded: 1900, militaryKilled: 240, civilianKilled: 50, source: "Hengaw" },
    { date: "2026-03-17", country: "Iran", side: "Iran", killed: 270, wounded: 1951, militaryKilled: 220, civilianKilled: 50, source: "HRANA" },
    // US casualties
    { date: "2026-02-28", country: "Kuwait", side: "US", killed: 6, wounded: 4, militaryKilled: 6, civilianKilled: 0, source: "CENTCOM" },
    { date: "2026-03-02", country: "Multiple", side: "US", killed: 1, wounded: 8, militaryKilled: 1, civilianKilled: 0, source: "CENTCOM" },
    { date: "2026-03-13", country: "Iraq", side: "US", killed: 6, wounded: 0, militaryKilled: 6, civilianKilled: 0, source: "CENTCOM" },
    // Israel casualties
    { date: "2026-02-28", country: "Israel", side: "Israel", killed: 1, wounded: 27, militaryKilled: 0, civilianKilled: 1, source: "Israeli Health Ministry" },
    { date: "2026-03-01", country: "Israel", side: "Israel", killed: 9, wounded: 120, militaryKilled: 0, civilianKilled: 9, source: "Israeli Health Ministry" },
    { date: "2026-03-06", country: "Israel", side: "Israel", killed: 8, wounded: 280, militaryKilled: 2, civilianKilled: 6, source: "Israeli Health Ministry" },
    // Lebanon casualties
    { date: "2026-03-01", country: "Lebanon", side: "Lebanon", killed: 320, wounded: 800, militaryKilled: 180, civilianKilled: 140, source: "Al Jazeera" },
    { date: "2026-03-10", country: "Lebanon", side: "Lebanon", killed: 400, wounded: 900, militaryKilled: 220, civilianKilled: 180, source: "Al Jazeera" },
    { date: "2026-03-17", country: "Lebanon", side: "Lebanon", killed: 248, wounded: 732, militaryKilled: 150, civilianKilled: 98, source: "Al Jazeera" },
    // Gulf states
    { date: "2026-02-28", country: "Bahrain", side: "Gulf States", killed: 8, wounded: 14, militaryKilled: 3, civilianKilled: 5, source: "Reuters" },
    { date: "2026-03-01", country: "Oman", side: "Gulf States", killed: 2, wounded: 5, militaryKilled: 0, civilianKilled: 2, source: "Reuters" },
    { date: "2026-03-24", country: "UAE", side: "Gulf States", killed: 11, wounded: 169, militaryKilled: 2, civilianKilled: 9, source: "UAE Defense Ministry / Al Jazeera" },
    // Updated Iran casualties (March 21-27)
    { date: "2026-03-21", country: "Iran", side: "Iran", killed: 200, wounded: 1800, militaryKilled: 150, civilianKilled: 50, source: "HRANA" },
    { date: "2026-03-24", country: "Iran", side: "Iran", killed: 275, wounded: 1600, militaryKilled: 200, civilianKilled: 75, source: "HRANA / Reuters" },
    { date: "2026-03-27", country: "Iran", side: "Iran", killed: 230, wounded: 1400, militaryKilled: 170, civilianKilled: 60, source: "Iran Health Ministry / WaPo" },
    // Updated Israel casualties
    { date: "2026-03-21", country: "Israel", side: "Israel", killed: 0, wounded: 78, militaryKilled: 0, civilianKilled: 0, source: "Al Jazeera (Dimona strike)" },
    { date: "2026-03-28", country: "Israel", side: "Israel", killed: 1, wounded: 45, militaryKilled: 0, civilianKilled: 1, source: "Jerusalem Post" },
    // Updated Lebanon casualties
    { date: "2026-03-24", country: "Lebanon", side: "Lebanon", killed: 148, wounded: 497, militaryKilled: 100, civilianKilled: 48, source: "Al Jazeera" },
    // Iraq PMF casualties
    { date: "2026-03-20", country: "Iraq", side: "Iraq", killed: 96, wounded: 200, militaryKilled: 85, civilianKilled: 11, source: "Iraqi Health Authorities" },
    // ===== WEEK 2: April 1-4 casualties =====
    { date: "2026-04-01", country: "Iran", side: "Iran", killed: 310, wounded: 1900, militaryKilled: 230, civilianKilled: 80, source: "HRANA" },
    { date: "2026-04-03", country: "Iran", side: "Iran", killed: 180, wounded: 1200, militaryKilled: 140, civilianKilled: 40, source: "HRANA" },
    { date: "2026-04-01", country: "Multiple", side: "US", killed: 2, wounded: 45, militaryKilled: 2, civilianKilled: 0, source: "Military Times / CENTCOM" },
    { date: "2026-04-01", country: "Israel", side: "Israel", killed: 2, wounded: 65, militaryKilled: 0, civilianKilled: 2, source: "IDF / Critical Threats" },
    { date: "2026-04-01", country: "Lebanon", side: "Lebanon", killed: 85, wounded: 310, militaryKilled: 50, civilianKilled: 35, source: "Al Jazeera" },
    { date: "2026-04-01", country: "Bahrain", side: "Gulf States", killed: 3, wounded: 18, militaryKilled: 1, civilianKilled: 2, source: "Critical Threats" },
    { date: "2026-04-01", country: "Iraq", side: "Iraq", killed: 8, wounded: 15, militaryKilled: 8, civilianKilled: 0, source: "Critical Threats" },
  ];

  for (const c of casualtyData) {
    db.insert(casualties).values(c).run();
  }

  // =============================================
  // INFRASTRUCTURE DAMAGE
  // =============================================
  const infraData = [
    { date: "2026-03-07", country: "Iran", category: "residential", count: 5535, description: "Residential units targeted by US-Israeli strikes", source: "Iranian Red Crescent" },
    { date: "2026-03-07", country: "Iran", category: "commercial", count: 1041, description: "Commercial units damaged", source: "Iranian Red Crescent" },
    { date: "2026-03-07", country: "Iran", category: "medical", count: 14, description: "Medical centres struck", source: "Iranian Red Crescent" },
    { date: "2026-03-07", country: "Iran", category: "school", count: 65, description: "Schools damaged or destroyed", source: "Iranian Red Crescent" },
    { date: "2026-03-07", country: "Iran", category: "humanitarian", count: 13, description: "Red Crescent centres damaged", source: "Iranian Red Crescent" },
    { date: "2026-03-16", country: "Iran", category: "military", count: 7000, description: "Military locations struck per CENTCOM", source: "CENTCOM" },
    { date: "2026-03-01", country: "Israel", category: "residential", count: 45, description: "Residential buildings damaged by Iranian missiles", source: "Israeli authorities" },
    { date: "2026-03-01", country: "Lebanon", category: "residential", count: 380, description: "Residential buildings destroyed in Israeli strikes", source: "Al Jazeera" },
    { date: "2026-02-28", country: "Bahrain", category: "military", count: 3, description: "US military facilities damaged", source: "CENTCOM" },
    // Week 2 infrastructure
    { date: "2026-04-01", country: "Iran", category: "military", count: 12300, description: "Military targets struck per CENTCOM (cumulative since Feb 28)", source: "CENTCOM" },
    { date: "2026-04-01", country: "Iran", category: "naval", count: 155, description: "Iranian naval vessels destroyed or damaged (cumulative)", source: "CENTCOM" },
    { date: "2026-04-01", country: "Iraq", category: "military", count: 4, description: "PMF brigade facilities struck in Tal Afar and Erbil", source: "Critical Threats" },
  ];

  for (const i of infraData) {
    db.insert(infrastructure).values(i).run();
  }

  console.log("Database seeded with conflict data.");
}
